-- Run this in Supabase SQL Editor if registration fails with:
-- 42501: new row violates row-level security policy for table "students"
--
-- This project uses Streamlit-side custom login, not Supabase Auth users.
-- These policies allow the app's anon/authenticated API key to read and create
-- student rows while requiring both face and voice biometrics at registration.

create table if not exists public.teachers (
    teacher_id bigint generated by default as identity primary key,
    name text not null,
    username text not null unique,
    email_id text not null unique,
    password text not null,
    created_at timestamp with time zone default now()
);

alter table public.students enable row level security;
alter table public.teachers enable row level security;
alter table public.subjects enable row level security;
alter table public.subject_students enable row level security;

grant select, insert, update on public.students to anon, authenticated;
grant select, insert, update, delete on public.teachers to anon, authenticated;
grant select on public.subjects to anon, authenticated;
grant select, insert on public.subject_students to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

drop policy if exists "app can read students" on public.students;
create policy "app can read students"
on public.students
for select
to anon, authenticated
using (true);

drop policy if exists "app can register students with biometrics" on public.students;
create policy "app can register students with biometrics"
on public.students
for insert
to anon, authenticated
with check (
    face_embedding is not null
    and voice_embedding is not null
);

drop policy if exists "app can update student biometrics" on public.students;
create policy "app can update student biometrics"
on public.students
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "app can read teachers" on public.teachers;
create policy "app can read teachers"
on public.teachers
for select
to anon, authenticated
using (true);

drop policy if exists "admin app can create teachers" on public.teachers;
create policy "admin app can create teachers"
on public.teachers
for insert
to anon, authenticated
with check (
    name is not null
    and username is not null
    and email_id is not null
    and password is not null
);

drop policy if exists "admin app can update teachers" on public.teachers;
create policy "admin app can update teachers"
on public.teachers
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "admin app can delete teachers" on public.teachers;
create policy "admin app can delete teachers"
on public.teachers
for delete
to anon, authenticated
using (true);

drop policy if exists "app can read subjects" on public.subjects;
create policy "app can read subjects"
on public.subjects
for select
to anon, authenticated
using (true);

drop policy if exists "app can read subject enrollments" on public.subject_students;
create policy "app can read subject enrollments"
on public.subject_students
for select
to anon, authenticated
using (true);

drop policy if exists "app can auto enroll students" on public.subject_students;
create policy "app can auto enroll students"
on public.subject_students
for insert
to anon, authenticated
with check (true);
