create table if not exists public.feedback (
    feedback_id bigint generated by default as identity primary key,
    student_id bigint not null,
    raw_text text not null,
    sentiment text not null check (sentiment in ('Positive', 'Neutral', 'Negative')),
    confidence_score double precision not null default 0 check (
        confidence_score >= 0
        and confidence_score <= 1
    ),
    created_at timestamptz not null default now()
);

alter table public.feedback
    add column if not exists subject_id bigint;

alter table public.feedback
    add column if not exists subject_name text;

alter table public.feedback
    add column if not exists themes jsonb not null default '[]'::jsonb;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'feedback_student_id_fkey'
    ) then
        alter table public.feedback
            add constraint feedback_student_id_fkey
            foreign key (student_id)
            references public.students(student_id)
            on delete cascade;
    end if;

    if not exists (
        select 1
        from pg_constraint
        where conname = 'feedback_subject_id_fkey'
    ) then
        alter table public.feedback
            add constraint feedback_subject_id_fkey
            foreign key (subject_id)
            references public.subjects(subject_id)
            on delete set null;
    end if;
end $$;

create index if not exists idx_feedback_created_at
    on public.feedback (created_at desc);

create index if not exists idx_feedback_subject_created_at
    on public.feedback (subject_id, created_at desc);

create index if not exists idx_feedback_subject_name_created_at
    on public.feedback (subject_name, created_at desc);

create index if not exists idx_feedback_student_created_at
    on public.feedback (student_id, created_at desc);

alter table public.feedback enable row level security;

drop policy if exists "service role can manage feedback" on public.feedback;
create policy "service role can manage feedback"
    on public.feedback
    for all
    using (auth.role() = 'service_role')
    with check (auth.role() = 'service_role');
